#Release environment
env = Environment(CC = 'clang', 
                  CCFLAGS = '-g -W -Wall')

env.Append(LIBS = ['SDL', 'X11'])

coreObjects =env.Object( Glob('core/*.c'))
mainObject = env.Object( Glob('desktop/main.c'))
allObjects = mainObject + coreObjects

env.Program('gb',allObjects)

#Test environment

