#Release environment
env = Environment(CC = 'gcc', 
                  CCFLAGS = '--std=c99 -O3 -W -Wall')

env.Append(LIBS = ['SDL', 'X11'])

coreObjects =env.Object( Glob('core/*.c'))
nonCoreObjects = env.Object( Glob('shared_libs/SDL/*'))
mainObject = env.Object( Glob('platforms/standard/main.c'))
allObjects = mainObject + coreObjects + nonCoreObjects

env.Program('gb_emu',allObjects)

#Test environment
#coreTestEnv = Environment(CC = 'clang')
#cpuTestObjects = env.Object( Glob('core/memory.c')) + env.Object( Glob('core/IO.c')) + env.Object( Glob('core/timers.c'))
#coreTestObject = env.Object( Glob('core/tests/cpuTests.c'))
#allObjects = cpuTestObjects + coreTestObject

#coreTestEnv.Program('cpuTests', allObjects)
